### ISSUE TITLE
Serialization of Enum type should use values rather than keys

### ISSUE THREAD

**Issue by cypreess** [ramonhagenaars/jsons#18]
Given the following example Enum type:
```
from enum import Enum

class TestEnum(Enum):
    KEY = 'value`

```

`jsons.dumps(TestEnum.KEY)` will result in `"KEY"` (Deserialization works correctly). 

However, this is behavior is a little bit irrational in regards to what enum is (used to be in C :) ). Enums classically are used to map some "codenames" for binary values (like numbers 0, 1, 2, 3). Therefore the value of enum should be binary representation generally used in serialization and keys should be something assigned for it on the high level (on runtime/ in the codebase).

---
Update: just for a reference standard lib json module does not serialize Enum's at all.

**Comment by ramonhagenaars** [comment]
Hi cypreess, thanks for the issue.

The choice for serializing the key rather than the value of an enum was made because of the readability of the serialized output.

Consider having the following construction:
```python
class Pet(Enum):
    CAT = 1
    DOG = 2

@dataclass
class Person:
    name: str
    pet: Pet
```
And:
```python
p = Person('John', Pet.CAT)
jsons.dump(p)
```
This results in:
```python
{'name': 'John', 'pet': 'CAT'}
```
Rather than:
```python
{'name': 'John', 'pet': 1}
```
The former is more self-explaining.

You can still serialize enums by their key if you wanted to:

```python
jsons.dump(Pet.CAT, use_enum_name=False)
jsons.load(1, use_enum_name=False)
```

**Comment by cypreess** [comment]
7. Readability counts.
