### ISSUE TITLE
[bug] or [not a bug] @property serialization goes deep into recursion

### ISSUE THREAD

**Issue by arpanetus** [ramonhagenaars/jsons#37]
I don't really know, whether is a bug or it's ok. 
Anyway, adding some decorator to not to serialize *field_name* would be great, I think. 
![image](https://user-images.githubusercontent.com/14979358/55307552-abb43200-5479-11e9-8d13-f821e381cd44.png)

**Comment by ramonhagenaars** [comment]
Hi arpanetus. This behavior is caused by ``jsons`` also serializing properties, which in your case results in a stack overflow due to recursion. It is expected behavior.

There are multiple options for you to obtain what you want.

The first option is to not include properties at all, using the ``strip_properties`` parameter:
```python
@dataclass
class BaseModel:
    @property
    def encoded(self):
        return jsons.dumpb(self, strip_properties=True)
```

The second option is to inherit from ``JsonSerializable``:
```python
@dataclass
class BaseModel(JsonSerializable):
    ...
```
To encode an instance of the above, just do:
```python
encoded = base_model_inst.dumpb()
```

The third option is to omit the ``encoded`` property entirely and just do:
```python
encoded = jsons.dumpb(base_model_inst)
```

**Comment by arpanetus** [comment]
:+1: , thank you a lot!
