### ISSUE TITLE
Extra Parameters are set as new class variables

### ISSUE THREAD

**Issue by ahmetkucuk** [ramonhagenaars/jsons#62]
When I try to deserialize with extra parameters, the library creates a new variable in the object. I expect it to not create any new variables and not throw any exceptions.

```
>>> from dataclasses import dataclass
>>> import jsons
>>> 
>>> @dataclass
... class A:
...     x: int
... 
>>> a = jsons.load({'x': 1, 'y': 'abc'}, A)
>>> a.y
'abc'
>>> import dataclasses
>>> dataclasses.asdict(a)
{'x': 1}
```

I guess this happens in `_set_remaining_attrs`. I suggest making this call optional. 
OR
When we serialize it again, it should ignore these fields.

**Comment by ramonhagenaars** [comment]
Hi ahmetkucuk. This behavior is by design, because there may be attributes on an object that did not originate from an argument. For example:
```python
class A:
    def __init__(self, x: int):
        self.x = x
        self.y = 'abc'  # Not an argument, still an attribute.
```
Dumping and loading an instance of such a class should result in an equivalent instance.

As you probably already know, you can use strict-mode ``jsons.load({'x': 1, 'y': 'abc'}, A, strict=True)``. However, that raises an exception upon encountering an unexpected attribute.

As an alternative, you can define ``slots`` to let jsons know what attribites you are expecting. For example:
 ```python
@dataclass
class A:
    __slots__ = ['x']
    x: int

loaded = jsons.load({'x': 1, 'y': 'abc'}, A)  # abc is skipped, no exception is raised.
```

**Comment by ahmetkucuk** [comment]
Thank you for the suggestion.

I am using `dataclass(frozen=True)` and it works!
